jumperexchange/jumper-exchange

- src/components/Swap.css
- src/components/Swap.tsx
- src/services/balanceService.ts
- src/services/utils.ts
`refreshBalances` is not yet used to refresh the balance, perhaps this could be triggered every few seconds.
> Show own funds when defining a swap

- src/components/Clock.tsx
- src/components/Swap.css
- src/components/Swap.tsx
- src/components/Swapping.tsx
- src/services/connext.ts
> add process timer

- package.json
- src/components/nxtp/SwappingNxtp.tsx
- src/services/nxtp.tsx
- yarn.lock
Updates for prod to bypass develop changes.
> Connext prod updates

- src/AppXpollinate.tsx
- src/types/shared/coins.types.ts
Let me know if I did this correctly @maxklenk - happy to change the PR if needed
> Add support for Arbitrum DAI in xPollinate liquidity table

- package.json
- src/components/Swap.tsx
- src/services/LIFI/LIFI.spec.ts
- src/services/LIFI/Lifi.ts
- src/services/LIFI/typeguards.ts
- yarn.lock
- ADD LIFI class
- ADD `findRoutes(deposit, withdraw)` method
- ADD tests for `findRoutes(deposit, withdraw)`
- MODIFY `Swap.tsx` to work with the additions mentioned above
> LF-58: SDK wrap backend calls

- src/components/nxtp/SwappingNxtp.tsx
- src/components/nxtp/TransactionsTableNxtp.tsx
- src/services/nxtp.tsx
Made some modifications to the messaging in the modal, etc.
- "Open Wallet to Confirm Transaction" for send tx step to make it more clear
- "Claim Funds" is now the claiming button message. Set width to maximum within the table, making it even bigger
- Added message "If this step takes longer than 5m, please refresh the page." at both waiting steps
> update messages for transfer process steps

- src/components/nxtp/SwapXpollinate.css
- src/components/nxtp/SwapXpollinate.tsx
Made fee breakdown a little bit more descriptive/informative, and included relayer fee in calculation
> Add relayer fee in fee breakdown

- src/components/nxtp/SwapXpollinate.css
- src/components/nxtp/SwapXpollinate.tsx
- src/services/nxtp.tsx
- yarn.lock
- added a fee breakdown element (dropdown)
- has info for each type of fee
- relayer fee is now accounted for in the "toAmount" box
- fixed fee calculation issue with changing decimals
- if the input/depositAmount is 0 (or <0, ergo invalid):
- swap button will display "Enter Amount"
- we will no longer query auctions
> Add fee breakdown; include relayer fees

- src/components/SwapForm.tsx
[LF-108](https://lifi.atlassian.net/jira/software/projects/LF/boards/1?selectedIssue=LF-108)
> LF-108: Disable MAX amount if no deposit token selected

- src/components/ChainSelect.tsx
- src/components/Swap.tsx
- src/components/SwapForm.tsx
- src/components/TokenSelect.tsx
Included:
- query parameters are used to fill the form
- the form settings update the query parameter
- if no default chain is specified the chain of the connected wallet is used
- a switch chain button is shown if users are on another chain then the selected one
- gas balances are checked for transaction included in the route
> LF-47: Parse and Set query parameters to define swap

- src/components/Dashboard.tsx
[LF-154](https://lifi.atlassian.net/jira/software/projects/LF/boards/1?selectedIssue=LF-154)
> fix(Dashboard): fix coin aggregations

- src/components/TransactionsTable.tsx
Users have issues understanding what they should do when an action is required. This PR highlights the button they should click to resume a swap.
> LF-190: improve button clickability

- package.json
- yarn.lock
Needs to be updated with release version of sdk when sdk PRs are merged and released
> chore: update lifi sdk version

- src/services/utils.ts
- src/services/utils.unit.spec.ts
fix(SwapForm): render BigNumbers with value 0 as 0.0 (#168)
> Release number formatting fix

- src/components/Swap.tsx
- src/components/TransactionsTable.tsx
- src/services/localStorage.fixture.ts
- src/services/localStorage.ts
- src/services/localStorage.unit.spec.ts
- fix(Swap): sort all transactions new -> old
- fix: show cancelled routes in historical routes
> fix: fix sorting of routes and show cancelled routes in historical routes

- .env.development.stagingBackend
- package.json
- src/components/Swapping.tsx
- yarn.lock
Depends on https://github.com/lifinance/sdk/pull/5
yarn link the sdk package with the mentioned SDK PR
> refactor(Swapping): use new StatusManager class

- src/services/utils.ts
Those functions are now part of the SDK and they are not needed in the FE anymore
> refactor: remove unused code that is now in the sdk

- .eslintignore
- .prettierignore
- public/widget.css
- public/widget.js
iframe integration script gets new functionality including drawer mode 💥
> LF-253: iframe integration script

- src/components/Swapping.tsx
- src/services/processRenderer.tsx
Show more helpful error messages to the user if transactions fail
> feat(Swapping): improve rendering of swap errors

- src/types/defaultToken.types.ts
We market that this token is trending and you can swap to it.
> Added a token for marketing purposes.

- src/components/Swapping.tsx
SDK PR: https://github.com/lifinance/sdk/pull/28
> fix: typo in getEthereumDecryptionHook

- src/components/Swap.tsx
The useEffect hook used to restart routes after pageload was also triggered when the web3 library changed. This also happens on chain switch. Since we only want to restart on pageload a new flag was introduced to track if it was already restarted or not.
> fix: prevent resume routes on chain switch

- src/types/defaultToken.types.ts
Zord4n added LOOKS for "daily token we support post"
> Added LOOKS for marketing purposes

- src/types/defaultToken.types.ts
Added $MELT - Defrost finance token for marketing purposes
> feat: Add $MELT token

- src/types/defaultToken.types.ts
Added $TOMB token on Fantom for marketing purposes
> feat: add $TOMB token

- src/types/defaultToken.types.ts
Added $BOLE token on BSC for marketing purposes
> feat: add $BOLE token

- src/types/defaultToken.types.ts
Added $DNL on BSC for marketing purposes
> feat: add $DNL token

- src/components/Swap.css
- src/components/Swapping.tsx
> feat: extended swap successful message

- src/components/Swap.tsx
When adding custom token via a url parameter, they should be loaded from the server.
> fix: sync custom tokens with server

- src/components/Swap.tsx
- src/components/Swapping.tsx
[LF-420](https://lifi.atlassian.net/browse/LF-420)
> fix(Swapping): fix alignment of native token results

- package.json
- src/components/ChainSelect.tsx
- src/components/SwapForm.tsx
- yarn.lock
- chore: update sdk version
- fix: fix dependencies to sdk dependencies
> feat: use sdk with updated bridging behaviour

- src/App.tsx
- src/components/Dashboard.tsx
- src/components/Swap.css
> feat: add banner and link to transferto.xyz

- .env
- package.json
- src/App.tsx
- src/components/Dashboard.tsx
- src/components/Swap.css
- src/components/web3/connectors.ts
- src/config/connectors.ts
- yarn.lock
This will add the banner to staging and allow using all new bridges and exchanges
> Deploy to Staging

- .env
- package.json
- src/components/web3/connectors.ts
- src/config/connectors.ts
- yarn.lock
- config: add more mainnet RPCs
- feat: handle multiple rpc urls
> feat: handle multiple rpc urls

- .github/workflows/build_others.yml
- .github/workflows/deploy_lifinance_mainnet_production.yml
- .github/workflows/deploy_lifinance_mainnet_staging.yml
- .github/workflows/deploy_lifinance_mainnet_testing.yml
- Revert "chore: remove old github actions"
- build: remove data unlocker
> build: reenable ssh deployment

- .github/workflows/deploy_lifinance_mainnet_production.yml
- .github/workflows/deploy_lifinance_mainnet_staging.yml
- .github/workflows/deploy_lifinance_mainnet_testing.yml
* Revert "chore: remove old github actions"
This reverts commit f6188fdbe57d2b8ff03ec8f5c19bcafd34529a77.
* build: remove data unlocker
> build: reenable ssh deployment (#254)

- package.json
- src/LiFi.ts
- src/components/Swap.css
- src/components/Swap.tsx
- src/components/SwapUkraine.tsx
- src/components/Swapping.tsx
- yarn.lock
We first need to release the breaking changes in the SDK: https://github.com/lifinance/sdk/commit/67cff834aa7643234ec43626489059869e018787
> feat: adjust to new LiFi SDK structure

- .env
- src/assets/wallets/blockwallet.svg
- src/components/web3/ConnectButton.tsx
feat: add blockwallet support (#276):
* feat: add blockwallet info
* feat: add wallet identity popover
* chore: remove unused imports
> Staging Deployment

- src/components/Route.tsx
https://lifi.atlassian.net/browse/LF-692
> feat: hide usd price if not available

- README.md
> Li.Li -> Li.Fi

- src/App.tsx
> refactor: add submenu for showcases

- package.json
- src/components/Swapping.tsx
- src/components/SwappingEtherspot/StepRenderers/EtherspotStep.tsx
- src/components/SwappingEtherspot/StepRenderers/LIFIRouteSteps.tsx
- src/components/SwappingEtherspot/StepRenderers/SimpleTransferStep.tsx
- src/components/SwappingEtherspot/SwappingCarbonOffset.tsx
- src/components/SwappingEtherspot/SwappingEtherspotKlima.tsx
- src/hooks/Etherspot/klimaStakingExecutor.ts
- src/hooks/Etherspot/offsetCarbonExecutor.ts
- src/services/localStorage.fixture.ts
- src/services/processRenderer.tsx
- yarn.lock
> refactor!: use sdk v1.0.0-beta.2

- src/components/Swap.tsx
> fix: default token loading

- src/components/Swap.tsx
> fix: available exchanges

- src/components/Swap.tsx
- src/components/SwapCarbonOffset.tsx
- src/components/SwapEtherspotKlimaZap.tsx
- src/components/SwapUkraine.tsx
> fix: to token selection and chain autoselect

- .env
- src/components/web3/connectors.ts
- src/config/connectors.ts
The default one doesn't really work
> fix(Aurora): use infura RPC

- src/hooks/useNavConfig.tsx
Ticket: https://lifi.atlassian.net/browse/LF-1862
> chore: adjust developers link to lifi-docs

- README.md
- docs/sdk-guide.md
> Fix: typos

- src/components/EmbedViews/SwapCarbonOffsetEmbed.tsx
- src/components/EmbedViews/SwapEtherspotKlimaZapEmbed.tsx
- src/components/HistoryMigration.tsx
- src/components/SwapCarbonOffset.tsx
- src/components/SwapCarbonOffsetV2.tsx
- src/components/SwapEtherspotKlimaZap.tsx
- src/components/SwapKlimaStakeV2.tsx
- src/components/SwapUkraine.tsx
- src/components/SwapV1.tsx
- src/config/connectors.ts
- src/services/utils.ts
* refactor: replace deepClone with native structuredClone
* fix: update history migration
> Production Release (#487)

- packages/dapp/package.json
- packages/dapp/src/const/MenuConfig/MainMenu/Main-MenuItems.tsx
- packages/dapp/src/const/MenuConfig/MainMenu/Main-SubMenu-Developers.tsx
- packages/dapp/src/const/MenuConfig/MainMenu/Main-SubMenu-Showcases.tsx
- yarn.lock
Ticket: https://lifi.atlassian.net/browse/LF-2667
> fix: disable arcx pageload events manually

- packages/dapp/package.json
- packages/dapp/src/AppProvider.tsx
- packages/dapp/src/components/Navbar/NavbarTabsContainer.tsx
- packages/dapp/src/const/MenuConfig/MainMenu/Main-MenuItems.tsx
- packages/dapp/src/const/MenuConfig/MainMenu/Main-SubMenu-Language.tsx
- packages/dapp/src/const/MenuConfig/MainMenu/Main-SubMenu-Theme.tsx
- packages/dapp/src/const/MenuConfig/WalletMenu/Wallet-MenuItems.tsx
- packages/dapp/src/hooks/useWidgetConfig.ts
- packages/shared/src/atoms/ThemeSwitch/ThemeSwitch.tsx
- packages/shared/src/organisms/WalletManagementButtons/WalletManagementButtons.tsx
- packages/shared/src/theme/theme.ts
- yarn.lock
Ticket: https://lifi.atlassian.net/browse/LF-2682
> Lf 2682 jumper adjust arcx tracking config

- .github/workflows/build-deploy.yaml
Added `testnet` branch in GitHub Actions deployment (for [testnet.jumper.exchange](https://testnet.jumper.exchange))
> feat(actions): add testnet branch

- .husky/commit-msg
Ticket: https://lifi.atlassian.net/browse/LF-2757
> feat: add 'Merge' as option to husky commit-msg

- packages/dapp/src/components/DualWidget/DualWidget.style.tsx
- packages/dapp/src/components/DualWidget/DualWidget.tsx
No Ticket, quick & dirty - fix this layout to align items vertically in a grid
Solution: Make them use 12 cols
> fix: items should expand full width

- packages/dapp/src/components/OnRamper/OnRamper.tsx
Re-Iterating on Ticket: https://lifi.atlassian.net/browse/LF-2786
_Leeroy | Onramper, [12 May 2023, 10:14:59]:
You're appending apiKey with ? change ? > &_
> fix: parse on-ramper api key and more

- packages/dapp/src/components/Widgets/Widgets.style.tsx
Ticket: https://lifi.atlassian.net/browse/LF-3460
> fix: overflow bug full size screens

- packages/dapp/src/components/StatsCard/StatsCard.style.ts
- packages/dapp/src/components/WelcomeWrapper/WelcomeWrapper.tsx
- packages/dapp/src/i18n/en.json
Ticket: https://lifi.atlassian.net/browse/LF-3519
> Lf 3519 welcome page improvements

- packages/dapp/src/components/Navbar/NavbarTabsContainer.tsx
- packages/dapp/src/components/Widgets/Widgets.tsx
- packages/dapp/src/const/linkMap.tsx
- packages/dapp/src/i18n/en.json
- packages/dapp/src/pages/Refuel/index.tsx
- packages/dapp/src/pages/Swap/index.tsx
Ticket: https://lifi.atlassian.net/browse/LF-3465
> refactor: replace swap with exchange terminology

- packages/dapp/package.json
- packages/dapp/src/components/SupportModal/SupportModal.style.tsx
- packages/dapp/src/components/Widgets/WidgetEvents.ts
- yarn.lock
Ticket: https://lifi.atlassian.net/browse/LF-2089
> feat: add support button widget event for modal

- packages/dapp/src/components/StatsCard/StatsCard.tsx
- packages/dapp/src/i18n/en.json
Ticket: https://lifi.atlassian.net/browse/LF-3569
> chore: add translation to stats-card titles

- packages/dapp/src/components/Widgets/Widgets.tsx
- packages/shared/src/config.ts
Ticket: https://lifi.atlassian.net/browse/LF-3572
> chore: show welcome also if wallet is disconnected

- packages/dapp/src/components/StatsCard/StatsCard.tsx
- packages/dapp/src/components/WelcomeWrapper/WelcomeWrapper.tsx
- packages/dapp/src/index.tsx
- packages/shared/src/fonts/inter.css
- packages/shared/src/style/reset.style.ts
- packages/shared/src/theme/theme.ts
Ticket: https://lifi.atlassian.net/browse/LF-3570
For now, we replaced all existing GT-America fonts in use with the Inter font.
> style: remove gt-america for now

- packages/dapp/src/components/Widgets/Widgets.tsx
Ticket: https://lifi.atlassian.net/browse/LF-3790
> fix: local storage naming value (LF-3790)

- packages/dapp/src/components/Navbar/Menu/WalletMenu/WalletMenu.tsx
- packages/dapp/src/components/Navbar/MenuItemComponent.tsx
- packages/dapp/src/components/Navbar/NavbarTabsContainer.tsx
- packages/dapp/src/components/ThemeSwitch/ThemeSwitch.tsx
- packages/dapp/src/components/Widget/Widget.tsx
- packages/dapp/src/const/MenuConfig/useDevelopersContent.tsx
- packages/dapp/src/const/MenuConfig/useLanguagesContent.tsx
- packages/dapp/src/const/MenuConfig/useMainMenuContent.tsx
- packages/dapp/src/const/MenuConfig/useShowcasesContent.tsx
- packages/dapp/src/const/MenuConfig/useThemeContent.tsx
- packages/dapp/src/const/MenuConfig/useWalletSelectContent.tsx
- packages/dapp/src/hooks/userTracking/useInitUserTracking.ts
- packages/dapp/src/hooks/userTracking/useUserTracking.ts
- packages/dapp/src/types/userTracking.types.ts
- packages/shared/src/atoms/ChainSwitch/ChainSwitch.tsx
- packages/shared/src/organisms/WalletManagementButtons/WalletManagementButtons.tsx
Ticket: https://lifi.atlassian.net/browse/LF-3877
> refactor: PascalCase EventTrackingKeys (LF-3877)

- packages/dapp/src/components/Widget/Widget.tsx
- packages/dapp/src/components/Widgets/Widgets.tsx
https://lifi.atlassian.net/browse/LF-4078
> fix: show only recommended route on gas tab

- packages/dapp/package.json
- packages/shared/package.json
- yarn.lock
Bumping packages of widget and wallet-management
> chore: bump widget and wallet-mgmt packages

- packages/dapp/src/components/FeatureCards/FeatureCard.tsx
- packages/dapp/src/components/FeatureCards/FeatureCards.tsx
- packages/dapp/src/types/featureCardsRequest.ts
Ticket: https://lifi.atlassian.net/browse/LF-4586
> fix: handle undefined showOnce attribute

- packages/dapp/src/components/Navbar/Menu/ChainsMenu/ChainsMenu.tsx
- packages/dapp/src/components/Navbar/Menu/WalletMenu/WalletMenu.tsx
- packages/dapp/src/components/Navbar/NavbarMenu.tsx
- packages/dapp/src/components/Navbar/NavbarMenuDesktop.tsx
- packages/dapp/src/components/Navbar/NavbarMenuMobile.tsx
- packages/dapp/src/components/Navbar/NavbarTabsContainer.tsx
- packages/dapp/src/components/Widget/Widget.tsx
- packages/dapp/src/const/MenuConfig/useDevelopersContent.tsx
- packages/dapp/src/providers/ThemeProvider.tsx
Removed redundant `!!` boolean casts from variables which are already `boolean` in type
> fix: removed redundant boolean type casts

- packages/dapp/package.json
- yarn.lock
updated wallet management and lifi widget
> chore: update lifi pkgs

- packages/dapp/index.html
- packages/dapp/src/hooks/userTracking/useUserTracking.ts
Ticket: https://lifi.atlassian.net/browse/LF-4794
> chore: update raleon setup (LF-4794)

- packages/dapp/src/components/StatsCard/StatsCard.tsx
- packages/dapp/src/hooks/useChains.ts
- packages/dapp/src/hooks/useFetchDexsAndBridges.tsx
Ticket: https://lifi.atlassian.net/browse/LF-5028
> fix: stats-count up on welcome-screen

- packages/dapp/src/const/MenuConfig/useChainsContent.tsx
- packages/shared/src/atoms/ChainSwitch/ChainSwitch.tsx
Quick Fix for latest Merge: https://github.com/lifinance/jumper.exchange/commit/a4af547c7e4bef3b9c5b42a8af4a5630578fea20
> fix: add optional operator

- packages/dapp/src/components/ThemeSwitch/ThemeSwitch.tsx
- packages/dapp/src/hooks/index.ts
- packages/dapp/src/hooks/usePopperIsOpened.ts
- packages/shared/src/atoms/ChainSwitch/ChainSwitch.tsx
Ticket: https://lifi.atlassian.net/browse/LF-5174
[screen-capture-no-tooltip-on-open-menu.webm](https://github.com/lifinance/jumper.exchange/assets/43956540/62d8749b-9f95-475e-881e-34245c79932d)
> fix: deactivate tooltips on open menus

- packages/dapp/src/hooks/useBlockchainExplorerURL.ts
Ticket: https://lifi.atlassian.net/browse/LF-5175
> fix: blockchain explorer hook

- packages/dapp/src/const/MenuConfig/useWalletSelectContent.tsx
https://lifi.atlassian.net/browse/LF-3298
Hide browser wallets when for mobile devices
> fix: hide browser wallets for mobile

- packages/dapp/src/const/trackingKeys.ts
Ticket: https://lifi.atlassian.net/browse/LF-5216
> fix: trackingKeys for added token name and address

- packages/shared/src/organisms/WalletManagementButtons/WalletManagementButtons.tsx
Ticket: https://lifi.atlassian.net/browse/LF-5219
> fix: trigger trackEvent only on closed wallet-select-menu

- packages/dapp/src/hooks/useBlockchainExplorerURL.ts
- packages/dapp/src/hooks/useChains.ts
Ticket: https://lifi.atlassian.net/browse/LF-5207
> fix: query handling on blockchain-explorer hook

- packages/dapp/src/components/FeatureCards/FeatureCards.tsx
- packages/dapp/src/components/Navbar/Navbar.tsx
- packages/dapp/src/components/Widgets/Widgets.tsx
- packages/dapp/src/const/MenuConfig/useWalletSelectContent.tsx
- packages/dapp/src/stores/settings/SettingsStore.tsx
- packages/shared/src/config.ts
- packages/shared/src/types/settings.ts
Ticket: https://lifi.atlassian.net/browse/LF-5217
> fix: trigger handleGetStarted only on welcome screen

- packages/dapp/src/hooks/useChains.ts
Ticket: https://lifi.atlassian.net/browse/LF-5308
> fix: not throwing Error

- packages/dapp/src/const/trackingKeys.ts
> refactor: remove unused trackingKeys

- packages/dapp/src/components/FeatureCards/FeatureCard.style.tsx
- packages/dapp/src/components/FeatureCards/FeatureCard.tsx
- packages/dapp/src/types/featureCardsRequest.types.ts
Ticket: https://lifi.atlassian.net/browse/LF-5427
[feature-cards-update-screen-capture.webm](https://github.com/lifinance/jumper.exchange/assets/43956540/c42100d5-f5ff-472f-a365-07aed4606299)
> style: update feature cards

- packages/dapp/src/const/cookie3.ts
Ticket: https://lifi.atlassian.net/browse/LF-5564
> fix: Cookie3 remove staging flag

- packages/dapp/src/components/WelcomeScreen/WelcomeScreen.style.ts
- packages/dapp/src/components/Widget/Widget.style.ts
- packages/dapp/src/components/Widgets/Widgets.style.tsx
- packages/dapp/src/components/Widgets/Widgets.tsx
Ticket: https://lifi.atlassian.net/browse/LF-5627
> style: fix ui + ux issues related to welcome screen

- index.html
Ticket: https://lifi.atlassian.net/browse/LF-6609
> fix: remove duplicate og image

- src/components/Menus/LanguagesSubMenu/LanguageSubMenu.tsx
Ticket: https://lifi.atlassian.net/browse/LF-6688
Problem happened here: https://github.com/lifinance/jumper.exchange/commit/3ceb6c13a1e9c463ee782e05714cd8ef3542e7ea#r137902403
> fix: Language sub menu label

- src/components/Blog/BlogArticle/BlogArticle.style.ts
- src/components/Blog/BlogArticle/BlogArticle.tsx
- src/components/Blog/BlogArticleCard/BlogArticleCard.style.ts
- src/components/Blog/BlogArticleCard/BlogArticleCard.tsx
- src/components/Blog/CustomRichBlocks.tsx
- src/components/Blog/FeaturedArticle/FeaturedArticle.style.ts
- src/components/Blog/FeaturedArticle/FeaturedArticle.tsx
- src/types/strapi.ts
Ticket: https://lifi.atlassian.net/browse/LF-7220
> chore: blog optimizations

- src/components/illustrations/JumperLearnLogo.tsx
- src/components/illustrations/JumperLogo.tsx
Ticket: https://lifi.atlassian.net/browse/LF-7232
> fix: invalid dom properties fill-rule + clip-rule

- src/components/Blog/BlogArticlesBoard/BlogArticlesBoardTabs.tsx
- src/components/MessageCard/MessageCard.style.ts
- src/components/MultisigConfirmationModal/MultisigConfirmationModal.style.ts
- src/components/MultisigConnectedAlert/MultisigConnectedAlert.style.ts
- src/components/MultisigWalletHeaderAlert/MultisigWalletHeaderAlert.style.ts
- src/components/Navbar/NavbarTabs/NavbarTabs.tsx
- src/components/OnRamper/OnRamper.style.ts
- src/components/OnRamper/OnRamper.tsx
- src/components/Widgets/Widget.style.ts
- src/components/Widgets/Widget.tsx
Ticket: https://lifi.atlassian.net/browse/LF-7233
> style: apply updated widget width of 416px to related components

- src/components/Menu/Menu.style.ts
- src/components/Menu/MenuMobile.tsx
Ticket: https://lifi.atlassian.net/browse/LF-7246
> fix: adjust zIndex of mobile drawer

- src/components/Avatar/Avatar.style.ts
- src/components/Mask.style.ts
- src/components/Menus/WalletMenu/WalletCard.tsx
- src/components/Menus/WalletMenu/WalletMenu.style.ts
- src/components/Navbar/NavbarButtons/WalletManagementButtons.style.ts
- src/components/index.ts
Ticket: https://lifi.atlassian.net/browse/LF-7251
**Info: I could not get this centered 100% correctly!**
Testing:
- Background-Color (as seen in the image underneath) is not happening on code! But rather just for testing
- to test properly, I applied the following styling temporarily to the Span-Contaner: `span: {background-color: rgba(0,0,0,0.5}; border-radius: 44px}`
- attached image is based on a 200% zoom level + browser zoom
- so going into the nitty gritty details!
> fix: center chain badge on wallet avatar

- env.d.ts
- src/components/Blog/CTAs/InstructionsAccordion/InstructionsAccordionItem.tsx
- src/components/Lightbox/Lightbox.tsx
- src/pages/BlogPage.tsx
Ticket: https://lifi.atlassian.net/browse/LF-7523
> fix: order of blog articles to desc + images within article content

- env.d.ts
- src/components/Blog/CTAs/InstructionsAccordion/InstructionsAccordionItem.tsx
- src/components/Lightbox/Lightbox.tsx
- src/pages/BlogPage.tsx
Related to:
- fix: order of blog articles to desc + images within article content
> Production Release

- src/components/Menu/Menu.style.ts
Ticket: https://lifi.atlassian.net/browse/LF-7571
[fix-menu-screen-capture.webm](https://github.com/lifinance/jumper.exchange/assets/43956540/c8a00a7c-7dc2-4cc1-b639-16e3ac622bc2)
> fix: menus on tablet sizes

- src/components/Avatar/Avatar.style.ts
- src/components/Mask.style.ts
- src/components/Menus/EcosystemSelectMenu/EVMConnectButton.tsx
- src/components/Menus/EcosystemSelectMenu/SVMConnectButton.tsx
- src/components/Navbar/NavbarButtons/WalletManagementButtons.style.ts
Ticket: https://lifi.atlassian.net/browse/LF-7300
> style: adjust wallet buttons + badges

- .github/scripts/delete-feature.mjs
- .github/scripts/dotenv-to-json.mjs
- .github/scripts/update-feature-img-version.mjs
- .github/scripts/utils.mjs
- .github/workflows/delete-feature.yml
- .github/workflows/deploy-feature.yml
- Add 2 new workflow for nextjs feature branch deployment & deletion
- add scripts to manage feature branch deploy & delete
> feat: add label for nextjs feature env

- src/components/Menus/LanguagesSubMenu/useLanguagesContent.tsx
- src/components/Menus/MainMenu/useThemeSwitchTabs.tsx
- src/components/Menus/WalletSelectMenu/useWalletSelectContent.tsx
- src/components/Widgets/WidgetSkeleton.style.ts
- src/hooks/useWelcomeScreen.ts
- src/providers/ThemeProvider.tsx
Ticket: https://lifi.atlassian.net/browse/LF-7905
> fix: jumper glitch on first connection welcome screen

- .github/workflows/build-deploy.yaml
Auto update has been enabled for jumper-exchange, so the publish tag github action is not needed anymore
> remove publish tags action

- src/components/Navbar/NavbarTabs/NavbarTabs.tsx
- src/components/ProfilePage/ProfilePage.tsx
Ticket: https://lifi.atlassian.net/browse/LF-8007
> fix: disable active tab on learn page

- .github/workflows/build-deploy.yaml
- .github/workflows/deploy-feature.yaml
- Dockerfile
As we will change our infrastructure instance type (from x86 to arm), we need to build our images using multi-platform buildx
> feat: multi platform build

- src/components/WelcomeScreen/ToolCard/ToolCard.style.ts
> fix: lineheight of tools card counter

- src/components/FeatureCards/FeatureCard.style.tsx
- src/components/FeatureCards/FeatureCard.tsx
Ticket: https://lifi.atlassian.net/browse/LF-8798
> fix: feature-card typography colors

- src/components/FeatureCards/FeatureCards.tsx
- src/hooks/useSession.ts
> fix: reference error session-storage

- src/components/Blog/CTAs/InstructionsAccordion/InstructionsAccordionItem.tsx
> fix: show first instruction item in blog article

- Dockerfile
- tests/themeManipulation.spec.ts
https://lifi.atlassian.net/browse/LF-8850
> fix: remove platform from dockerfile

- tests/e2e.spec.ts
replaced old explorer URL with new one (scan.li.fi)
> feat: replace explorer URL to scan.li.fi

- playwright.config.ts
- tests/e2e.spec.ts
increase timeout for waiting Buy button on Buy widget
> feat: increase timeout for buy widget

- src/components/Superfest/SuperfestPage/CTA/MissionCTA.style.ts
- src/components/Superfest/SuperfestPage/CTA/MissionCTA.tsx
> fix: adjust icon button bg color on superfest

- src/app/layout.tsx
Ticket: https://lifi.atlassian.net/browse/LF-9288
> fix: multiple snackbars

- src/components/Widgets/WidgetEvents.tsx
- src/const/trackingKeys.ts
[LF-9317](https://lifi.atlassian.net/browse/LF-9317)
> fix: remove insurance

- src/components/PartnerThemeFooterImage.tsx
- src/hooks/useSuperfest.ts
- src/utils/replaceLocaleInUrl.ts
Ticket: https://lifi.atlassian.net/browse/LF-9520
> fix: add slash to url´s on language change

- playwright.config.ts
- tests/e2e.spec.ts
Added API test for feature cards
> feat: adding api test for feature cards

- src/app/[lng]/[partnerTheme]/layout.tsx
- src/app/[lng]/[partnerTheme]/page.tsx
> fix: notfound theme

- src/components/Superfest/SuperfestPage/SignatureCTA/SignatureCTA.tsx
- src/hooks/useMissionsAPY.ts
> chore: Update superfest turtle text

- src/components/Superfest/AvailableMissionsList/AvailableMissionsList.tsx
- src/providers/TranslationProvider.tsx
Fix to superfest bug where select chain kills the UI
> fix: Superfest chains filter bug

- package.json
- src/components/Menus/EcosystemSelectMenu/EVMConnectButton.tsx
- src/components/Menus/EcosystemSelectMenu/EcosystemSelectMenu.tsx
- src/components/Menus/WalletSelectMenu/WalletSelectMenu.tsx
- src/components/Menus/WalletSelectMenu/useWalletSelectContent.tsx
- src/config/coinbase.ts
- src/config/metaMask.ts
- src/config/walletConnect.ts
- src/hooks/useAccounts.ts
- src/hooks/useCombinedWallets.ts
- src/providers/WalletProvider/EVMProvider.tsx
- yarn.lock
Development env
Production env
Also, fixes [LF-9498](https://lifi.atlassian.net/browse/LF-9498)
> feat: improve wallets loading

- src/app/[lng]/(main)/buy/page.tsx
- src/app/[lng]/(main)/gas/page.tsx
- src/app/[lng]/(main)/page.tsx
- src/app/[lng]/[partnerTheme]/page.tsx
- src/components/Alerts/InfoAlert/InfoAlert.style.ts
- src/components/Alerts/InfoAlert/InfoAlertClickable.tsx
- src/components/MessageCard/MessageCard.style.ts
- src/components/Widgets/Widgets.style.tsx
Ticket: https://lifi.atlassian.net/browse/LF-9697
> fix: widget vertical jump glitch

- .github/workflows/build-docker.yaml
Basic build & push docker image workflow
> GCP github workflow

- src/components/Blog/CustomRichBlocks.tsx
- src/components/ProfilePage/QuestCard/QuestCard.tsx
- src/components/ProfilePage/QuestCarousel/QuestCarousel.tsx
- src/components/ProfilePage/QuestsCompleted/QuestsCompletedList.tsx
- src/components/Quests/ActiveQuestsMissionsCarousel/ActiveQuestsMissionsCarousel.tsx
- src/components/Quests/AvailableMissionsList/AvailableMissionsList.tsx
- src/components/Quests/QuestCard/QuestCard.tsx
- src/components/Quests/QuestPage/CTA/MissionCTA.tsx
- src/components/Quests/QuestPage/QuestsMissionPage.tsx
- src/components/Superfest/ActiveSuperfestMissionsCarousel/ActiveSuperfestMissionsCarousel.tsx
- src/components/Superfest/AvailableMissionsList/AvailableMissionsList.tsx
- src/components/Superfest/QuestCard/QuestCard.tsx
- src/components/Superfest/SuperfestPage/CTA/MissionCTA.tsx
- src/components/Superfest/SuperfestPage/SuperfestMisisonPage.tsx
- src/const/trackingKeys.ts
- src/hooks/useOngoingQuests.ts
Ticket: https://lifi.atlassian.net/browse/LF-9873
> chore: add track events to quest-card + mission-cta

- src/app/[lng]/(infos)/learn/[slug]/page.tsx
- src/app/[lng]/(infos)/learn/page.tsx
- src/app/ui/learn/LearnPage.tsx
- src/components/Blog/BlogArticle/BlogArticle.style.ts
- src/components/Blog/BlogArticle/BlogArticle.tsx
- src/components/Blog/BlogArticleCard/BlogArticleCard.style.ts
- src/components/Blog/BlogArticleCard/BlogArticleCard.tsx
- src/components/Blog/BlogAuthorSocials/BlogAuthorSocials.tsx
- src/components/Blog/BlogCarousel/CarouselContainer.tsx
- src/components/Blog/FeaturedArticle/FeaturedArticle.style.ts
- src/components/Blog/FeaturedArticle/FeaturedArticle.tsx
- src/components/IconButton.style.ts
- src/components/Lightbox/Lightbox.style.ts
- src/components/Lightbox/Lightbox.tsx
page learn before
page article before
page learn after
page article after
The little variant of the performance is mainly due to local lags
> feat: optimize seo

- src/components/FeatureCards/FeatureCards.tsx
Ticket: https://lifi.atlassian.net/browse/LF-10189
> fix: hide feature cards on welcome screen

- src/components/Portfolio/TotalBalance.tsx
- src/i18n/resources.d.ts
- src/i18n/translations/en/translation.json
Ticket: https://lifi.atlassian.net/browse/LF-10332
> chore: add balance info tooltip on portfolio

- Dockerfile
Ticket: https://lifi.atlassian.net/browse/LF-10299
> fix: sharp error in production

- src/components/ProfilePage/AddressBox/AddressBox.tsx
- src/components/ProfilePage/LevelBox/LevelBox.tsx
- src/components/ProfilePage/LevelBox/PointsDisplay.tsx
- src/utils/getAddressLabel.ts
- src/utils/walletDigest.ts
Ticket: https://lifi.atlassian.net/browse/LF-10420
> chore: show sol address and improve empty states

- src/components/Blog/BlogArticle/BlogArticle.style.ts
- src/components/Blog/BlogArticle/BlogArticle.tsx
Ticket: https://lifi.atlassian.net/browse/LF-10465
> style: height auto on blog article image for responsiveness

- src/app/[lng]/bridge/[segments]/page.tsx
- src/app/[lng]/bridge/sitemap.ts
- src/app/robots.ts
- src/app/ui/bridge/PopularBridgeSection.tsx
- src/middleware.ts
~~Unfortunately, nextjs does not support . in the URL, i am checking onto their discord, other point is fixed~~
not an issue anymore
> feat: Enhance popular bridges

- src/app/api/widget-review/route.tsx
- src/app/api/widget-selection/route.tsx
- src/components/ImageGeneration/Fields/QuoteField.tsx
- src/components/ImageGeneration/WidgetExecutionImage.tsx
- src/components/ImageGeneration/WidgetReviewImage.tsx
Ticket: https://lifi.atlassian.net/browse/LF-11231
> fix: widget image-generation feat placements

- src/components/Navbar/Navbar.style.tsx
- src/components/Navbar/WalletButton.tsx
Ticket: https://lifi.atlassian.net/browse/LF-11232
> chore: remove new label on multiportfolio and fix z indexes

- src/components/Widgets/Widget.tsx
Reverts jumperexchange/jumper-exchange#1737
> Revert "fix: remove toAddress from URL params"

- src/components/Widgets/Widget.tsx
working on all languages already
> fix: Update abstract text

- src/components/Widgets/Widget.tsx
Reverts jumperexchange/jumper-exchange#1738
> fix: remove toAddress from URL params

- .github/workflows/build-docker.yaml
This PR introduces a GitHub Actions workflow to automate the process of building and pushing Docker images to Google Artifact Registry (GAR) based on branch pushes.
> GCP Secret manager secret retrieval

- src/components/Leaderboard/LeaderboardEntry.style.ts
Ticket: https://lifi.atlassian.net/browse/LF-12419
> style: fix bg color of user entry on leaderboard

- .github/workflows/build-docker.yaml
Integrated gcp secrets manager with github actions in staging.
> feat: Added gcp sm in github actions staging

- next.config.mjs
- src/utils/strapi/StrapiApi.ts
Reverts jumperexchange/jumper-exchange#1804
> Revert "chore: strapiv5 intermediate migration step"

- src/components/FeatureCards/FeatureCards.tsx
Ticket: https://lifi.atlassian.net/browse/LF-12934
> fix: hide feature cards on mobile

- src/components/Navbar/Navbar.style.tsx
Ticket: https://lifi.atlassian.net/browse/LF-12931
> style: fix clickable logo area

- src/hooks/feature-cards/spindl/useSpindlCards.ts
Ticket: https://lifi.atlassian.net/browse/LF-13034
> chore: show spindl cards to all users

- src/hooks/tasksVerification/useVerifyTask.ts
> fix: task verification status handler

- src/hooks/useJumperTracking.ts
- src/hooks/userTracking/useUserTracking.ts
Ticket: https://lifi.atlassian.net/browse/LF-13330
> chore: add toAmountMin on transaction event

- src/app/[lng]/campaign/[slug]/page.tsx
- src/app/ui/quests/QuestMissionPage.tsx
- src/components/Campaign/CampaignPage.tsx
> fix: add missing slash in url to return to campaign page

- tests/settings.spec.ts
- tests/testData/settingsFunctions.ts
- improves the readability and maintainability of the settings playwright tests
- improves the coverage on verifying the settings
- covering resetting the settings
[LF-13727](https://lifi.atlassian.net/browse/LF-13727)
---
---
Bridge and Exchange selection and deselection in settings will be handled in a different ticket.
---
Tests pass in 7.6s
> [QA] LF-13727 refactor settings test and reset

- src/components/Link/Link.tsx
- src/components/Link/index.ts
- src/components/Navbar/Navbar.style.tsx
Issue: https://lifi.atlassian.net/browse/LF-13962
> fix: logo link triggers full page refresh

- package.json
- pnpm-lock.yaml
- src/components/QuestPage/SignatureCTA/SignatureCTA.tsx
- src/components/Superfest/SuperfestPage/SignatureCTA/SignatureCTA.tsx
- src/const/quests.ts
- src/hooks/useTurtleMember.ts
Issue: https://lifi.atlassian.net/browse/LF-12819
> Refactor: jumper integrate new turtle signature

- next.config.mjs
- src/app/lib/getArticles.ts
- src/app/lib/getArticlesByTag.ts
- src/app/lib/getFeaturedArticle.ts
- src/components/Blog/BlogArticle/BlogArticle.tsx
- src/components/Blog/BlogArticleCard/BlogArticleCard.tsx
- src/components/Blog/FeaturedArticle/FeaturedArticle.tsx
- src/types/strapi.ts
- src/utils/readingTime.ts
- src/utils/strapi/StrapiApi.ts
Issue: https://lifi.atlassian.net/browse/LF-14023
> feat: jumper improve blog article retrieval to not include the content for the article list

- src/components/ZapWidget/Deposit/DepositCard.tsx
- src/components/ZapWidget/ZapWidget.tsx
- src/i18n/resources.d.ts
- src/i18n/translations/bn/translation.json
- src/i18n/translations/en/translation.json
- src/i18n/translations/es/translation.json
- src/i18n/translations/fr/translation.json
- src/i18n/translations/hi/translation.json
- src/i18n/translations/id/translation.json
- src/i18n/translations/it/translation.json
- src/i18n/translations/ja/translation.json
- src/i18n/translations/ko/translation.json
- src/i18n/translations/pt/translation.json
- src/i18n/translations/th/translation.json
- src/i18n/translations/tr/translation.json
- src/i18n/translations/uk/translation.json
- src/i18n/translations/vi/translation.json
- src/i18n/translations/zh/translation.json
Issue: https://lifi.atlassian.net/browse/LF-14093
> fix: override toAddress with poolName for zap widget

- src/hooks/useMerklRewards.ts
Ticket: [Linked comment](https://lifi.atlassian.net/browse/LF-13535?focusedCommentId=21880)
> fix: check for valid evm address on merkl request
