jumperexchange/jumper-exchange

src/services/nxtp.execute.ts
nxtp sdk does not sync subgraphs before requesting the transfer quota. Until this is solved we manually sync them again by fetching the active transactions
=> Call getActiveTransactions to sync chains before requesting quota

src/App.tsx, src/components/Swap.tsx, src/components/web3/connectors.ts, src/services/balanceService.ts
The DeBank API token balances with too many decimals, which cases errors if users try to use all the tokens we think they have. We have now integrated multicall, which allows us to query balances directly from chain. I added this as the default way to get balances for both main- and testnets. If multicall is not available on a chain we instead fall back to query the balances of every token in a single call. The DeBank API is still used for the dashboard since we aim to show all the token a user have, in the swap we are only interested in token the user can actually swap or transfer (based on the dexs token lists).
=> LF-44: get balances from chain instead of debank

src/components/Swapping.tsx
After the users did a transfer or swap we show him his new token balance. When hovering the token name the user can add this token to his metamask wallet, because the wallet does not automatically show all tokens a user has. The native gas token on the other hand is always shown at the very top in the wallet, trying to add it to the wallet is not needed and doesn't work. So we should not show this option.
=> LF-70: do not try to add native gas token to wallet

.husky/pre-push, package.json, yarn.lock
To enable husky you have to run `yarn install` once. There is a `prepare` step which will set it up.
**Important**: This works only for yarn < v2. For yarn v2 we need to do some changes
=> 🐕  Fix husky configuration

src/components/Swapping.tsx, src/services/localStorage.ts
To have a better name for the LocalStorage key we switched from `activeRoute` to `routes`. To not loose any data a migration was added that moves any values from the old to the new key.
=> fix: do not overwrite historic routes when saving new ones

src/components/Swap.css, src/components/Swap.tsx, src/services/utils.ts
This should prevent these strange scenarios when you press the `MAX` button but the value differs from the balance
=> fix: use rounding function to render balance correctly

src/components/Swap.css, src/components/Swap.tsx, src/components/SwapForm.tsx
Users are often confused why the final amount differs from the one shown initially. For this reason we should provide a clear message telling them that this is just an estimation.
=> feat(SwapForm): show slippage tooltip at "to" amount

src/components/Swap.tsx, src/components/TransactionsTable.tsx
contains necessary logic to get new status on page load. 
Needs SDK PR: https://github.com/lifinance/sdk/pull/26
If SDK is not merged and released, no behaviour will change.
=> feat: check for execution status on page load

.github/workflows/build_others.yml
If people create a PR from their forked repository of by editing in Github directly no `push` event will be triggered to run the prettier and eslint checks. For those cases we need to run on `pull_request` events.
=> build: run workflow on pull_request events

src/App.tsx
[LF-349](https://lifi.atlassian.net/jira/software/c/projects/LF/boards/6?modal=detail&selectedIssue=LF-349&quickFilter=10)
The "Docs" button on Li.Finance is not very actionable. It should encourage to click on it -> Change the Button text to "Explore Docs"
=> feat: change Docs link to "Explore Docs"

src/components/Swap.css, src/components/Swap.tsx
Adds a padding at the bottom page to prevent the social buttons from overlapping the available routes on small screens
=> style: add bottom padding on mobile

src/components/Clock.tsx, src/components/Route.tsx, src/components/Swap.css, src/components/Swapping.tsx, src/services/utils.ts, src/services/utils.unit.spec.ts
This just shows the estimated duration for a route and for each step in a very simple way:
=> feat: show estimated duration for routes and steps

.env.development.developBackend, .env.development.stagingBackend, package.json
Since we now differentiate between staging and develop environment it makes more sense to use the develop stage for local development instead of the staging stage.
=> build: use develop instead of staging for local testing

src/components/Swap.tsx, src/components/Swapping.tsx
We want to use the /status endpoint in the SDK instead of the Connext SDK. For that reason we cannot allow encryption in the frontend anymore.
At a later point we will handle the encryption in the backend, for now we completely remove it from the user interface
=> feat: remove encryption functionality

src/components/Swap.tsx, src/components/SwapUkraine.tsx
CELO chain's native token is not on address zero: https://explorer.celo.org/token/0x471EcE3750Da237f93B8E339c536989b8978a438/token-transfers
So far we just assumed that the gas token is always on 0x0. Instead we should use the token configured in our chain list.
=> fix: use token defined in chain to do gas check

src/components/Swap.tsx
now that the connext ids are generated on the server we can keep routes after the modal has been opened
=> fix: keep routes after modal open

src/services/metamask.ts
the old implementation almost always returned false. Now its explicitly creating a promise to wait until the chainswitch event has been fired
=> fix: chain switch bug

src/components/Swap.tsx
The `Order` Type has been updated, if we can update the types for the the frontend we should do so as well.
=> feat: allow to select order of returned routes

src/components/Swapping.tsx
Fixed the alignment of the error buttons
Note: normally in this case only one button would be shown. not both. This is for demonstration only
=> style: fix alignment

src/components/TokenSelect.tsx, src/services/goplus.ts
We now have one more validation state: `Attention`. Go+ uses this for tokens which are not clearly risky but the user should be aware that the contract supports some additional functionality.
A custom list of trusted tokens and more chains Go+ supports have been added as well.
=> feat(go+): improve token validation parsing

.github/workflows/deploy.yml
- Updated docker official actions
- Using the official `yq` action instead of downloading the binary everytime
- using the new GitHub environment variables and api for storing outputs and branch name
=> Lf 1746 fix deprecation warnings and node version in GitHub actions

.env.development.developBackend, .env.lifinance-mainnet.develop
Using a new develop endpoint (develop.li.quest) in order to use the same DNS endpoint of our staging/production releases. If they are referenced in other parts and/or in different ways, let me know 🙂
=> fix: new develop endpoint

packages/dapp/src/components/DualWidget/DualWidget.tsx, packages/dapp/src/components/OnRamper/OnRamper.style.ts, packages/dapp/src/components/OnRamper/OnRamper.tsx
Issue: Default tab is always the new OnRamper buying widget.
We want the default to be either "Swap" or chosen depending on current URL.
[fix-default-tab.webm](https://user-images.githubusercontent.com/43956540/236174607-b2dc40f1-5d64-47a8-9e08-f72ff6f94f98.webm)
=> fix: default tab depending on url

packages/dapp/src/components/OnRamper/OnRamper.tsx
Ticket: https://lifi.atlassian.net/browse/LF-3282
**After adjusting the height to 560px, it is not scrollable anymore.**
=> fix: avoid scrolling, adjust onramper height

packages/dapp/src/components/Navbar/Navbar.tsx, packages/dapp/src/const/MenuConfig/useWalletSelectContent.tsx
Ticket: https://lifi.atlassian.net/browse/LF-3573
Fix: The Flag "welcomeScreenEntered" will now be set to true once a wallet is selected. As soon as the WalletConnect opens, the welcome screen disappears now.
[close-welcome-screen-on-wallet-selection-screen-capture.webm](https://github.com/lifinance/jumper.exchange/assets/43956540/137e5e48-8a9f-4204-85c2-e157d5f690b3)
=> bug: close welcomeScreen on wallet selection

packages/dapp/src/components/Navbar/Menu/WalletMenu/WalletMenu.tsx
Ticket: https://lifi.atlassian.net/browse/LF-4459
Fixed blurry Snackbar, because it was placed too close to Navbar.
Solution: Move it down 2px
=> style: fix blurry snackbar (LF-4459)

packages/dapp/src/components/Widget/Widget.tsx, packages/dapp/src/components/Widgets/Widgets.tsx, packages/dapp/src/const/linkMap.tsx, packages/dapp/src/const/tabsMap.ts
Ticket: https://lifi.atlassian.net/browse/LF-4488
Problem: Due to refactoring the url `jumper.exchange/gas` did not open the associated "Gas"-Widget. It only loaded on `jumper.exchange/refuel` because the property "WidgetSubVariant" and the url-names don´t match. E.g. "Swap" refers to widgetVariant "default" and "Gas" is referring to "refuel".
Solution: With this change, we can not only define specific url but allow multiple url´s to open certain Tabs.
=> fix: allow multiple urls for tab opening (LF-4488)

packages/dapp/src/components/Navbar/Menu/MainMenu/MainMenu.tsx, packages/dapp/src/const/MenuConfig/useMainMenuContent.tsx, packages/dapp/src/i18n/en/translation.json, packages/dapp/src/i18n/i18next.d.ts, packages/dapp/src/providers/I18nProvider.tsx, packages/dapp/src/types/i18n.types.ts
While updating Crowdin to the new language scheme, I noticed we left duplicated language keys in our translations and this PR fixes this.
@Abhikumar98 you might be interested.
=> fix: duplicated language keys

packages/dapp/src/i18n/index.ts
This is a hotfix to remove the german language from jumper. Main has to be merged back into develop after merging this branch in main.
=> chore: temporarily disable german

.github/workflows/delete-test-app.yaml, .github/workflows/deploy-test-app.yaml
- Adding the label will trigger the deployment
- Every push will trigger a new deployment as always
- Removing the label will delete the deployment
- Closing the PR will delete the labeled deployment as always
=> ci(actions): test features without push

packages/dapp/src/providers/WalletProvider.tsx
- fire event before resetting the current wallet
- remove GA4 from tracking wallet disconnects (for now)
Parameters that are "promoted" to custom dimensions apparently are not bound to the event they are send in. If more than one even use the same event parameter, all those parameter hits are counted as one. In our case, the data collected for  wallet connects and disconnects where counted "the same variable". Not per event 
The more you know.
=> fix: remove ga from wallet disconnect event

packages/dapp/src/components/FeatureCards/FeatureCard.style.tsx, packages/dapp/src/components/FeatureCards/FeatureCard.tsx, packages/dapp/src/types/featureCardsRequest.ts
Ticket: https://lifi.atlassian.net/browse/LF-5417
I have played with that Feature Card and updated some parts:
- it´s now picking up the cta label
- I adjusted the image css, like setting a max-height and such
Example Now:
Example Before:
I believe, things can still be more optimized and improved. But I´d like to get some inspiration from Design for that. I guess it´s working for now, but we could iterate on it again
=> chore: add cta label to feature-card

packages/dapp/src/components/Widgets/Widgets.style.tsx
Ticket: https://lifi.atlassian.net/browse/LF-5030
[welcome-screen-expanded-issues-screen-capture.webm](https://github.com/lifinance/jumper.exchange/assets/43956540/9a240bd5-f7c5-4035-9d6f-b6f3f2a43ff4)
Two issues being fixed here _(see attached video)_:
1.) In Dark-Mode: The opacity is just being applied to a width of 392px but when we got an expanded widget with routes showing, that opacity is just being applied to that area of 392px width, giving it an odd look.
2.) When there´s quite a lot of routes and then re-entering the welcome-screen, a user could actually scroll down and expose those routes which should be hidden.
=> fix: welcome screen issues on expanded widget

packages/dapp/src/hooks/userTracking/useUserTracking.ts, packages/dapp/src/providers/WalletProvider.tsx, packages/dapp/src/types/userTracking.types.ts
Ticket: https://lifi.atlassian.net/jira/software/c/projects/LF/boards/15?selectedIssue=LF-5937
Found a bug in the implementation that would prevent firing the correct wallet connection event to arcx and hotjar when a wallet would be undefined. 
Fix: passing the wallet as function parameter as we always have the wallet object in a manual connect event.
=> fix: pass wallet as function arg to trackConnectWallet

packages/dapp/src/components/FeatureCards/FeatureCard.style.tsx, packages/dapp/src/components/FeatureCards/FeatureCard.tsx, packages/dapp/src/types/featureCardsRequest.types.ts
Ticket: https://lifi.atlassian.net/browse/LF-5936
1.) Added two fields that can optionally be set:
- titleColor
- ctaColor --> this was previously configured in "displayConditions" JSON
2.) In the displayConditions JSON customization for styling related props was nested in "custom". There is only one adjustment at this time, after we now moved ctaColor to its own field. It's "theme" (previuosly named "mode") and is in first hierarchy of the JSON, not located anymore within "custom"-object.
=> style: add feature card fields to optimize colors

src/hooks/userTracking/useUserTracking.ts
GA was not properly called on wallet connection. 
This fix calls the appropriate function.
As we know when trackConnectWallet is being called, i removed the checks for `disableTrackingTool` from that function
=> fix: wallet tracking

src/components/Button/Button.style.ts, src/components/Menu/MenuDesktop.tsx, src/components/Menu/MenuItem.tsx, src/components/Menus/MainMenu/useMainMenuContent.tsx, src/components/Menus/WalletMenu/WalletCard.tsx, src/components/Menus/WalletMenu/WalletMenu.style.ts, src/components/Navbar/NavbarButtons/WalletManagementButtons.style.ts, src/theme/theme.ts
This PR introduces some style adjustments:
- Align Desktop menus with their anchor buttons. Menus now align with the right border of their summoning buttons. 
- Change Button color in menus to the secondary color. Adjusted the Theme to easily implement this and to carry that change across light and dark theme
=> style: Styling adjustments

src/components/Menus/EcosystemSelectMenu/EVMConnectButton.tsx, src/components/Menus/EcosystemSelectMenu/EcosystemSelectMenu.style.ts, src/components/Menus/EcosystemSelectMenu/EcosystemSelectMenu.tsx, src/components/Menus/EcosystemSelectMenu/SVMConnectButton.tsx, src/components/Menus/WalletMenu/WalletMenu.tsx
Ticket: https://lifi.atlassian.net/browse/LF-6933
Implements Vilens feedback on the wallet ecosystem select feature. It moves away from using the wallet icon as the main information on the ecosystem connect buttons towards the chain icons you can connect two. it smoothes over some paddings and margins in order to align the menus closer to the figma design. 
A couple of things have to be sorted out later as the figma contains some design inconsistencies:
- menu headers have different heights in the designs. This is not reflected here.  Vilen wants to spend some time working on the general jumper design language
- corners on wallet menus have different radii in the designs. Not implemented here Same reason as point above
=> feat: implement new ecosystems select style

src/components/FallbackError/FallbackError.tsx, src/components/Navbar/Navbar.tsx, src/components/Navbar/NavbarButtons/NavbarButtons.tsx, src/components/Navbar/NavbarButtons/WalletManagementButtons.tsx, src/components/Widgets/WidgetEvents.tsx, src/hooks/useAccounts.ts, src/hooks/useMultisig.ts, src/hooks/userTracking/useUserTracking.ts
Ticket: https://lifi.atlassian.net/browse/LF-6934
In order to provider a better UX and to give the user feedback on the success of his wallet connection, the wallet digest button should always show the last connected wallet.
=> feat: show last wallet first in wallet management

src/hooks/useMultisig.ts
I found an issue where we set the destination chain acquired from widget events for multisig configuration and then used this multisig configuration inside the widget wrapper component, firing a widget update on the widget event and creating some kind of loop. We should **avoid** this type of situation because it leads to collisions inside the widget, and in this case, it was possible to select the same **from** and **to** tokens. 
The usage of widget events should not trigger immediate widget re-render.
@dennyscode please investigate if there are other potential situations when widget events can trigger widget re-render.
=> fix: destination chain acquired from Widget Events should not update the widget component

next.config.mjs
Jira: [LF-8183](https://lifi.atlassian.net/browse/LF-8183)
Can be used with the Widget Branch on this PR -  https://github.com/lifinance/widget/pull/245
This should help using yarn link between widget and jumper
[LF-8183]: https://lifi.atlassian.net/browse/LF-8183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add alias to next config for .js extensions for yarn link

src/components/Menu/Menu.style.ts
=> fix: full width on menu item links

package.json, yarn.lock
- bump widget to enable bridge allowance
=> chore: bump widget to v 3.0.2

src/components/JoinDiscordBanner/JoinDiscordBanner.tsx, src/const/urls.ts, tests/e2e.spec.ts
```
Hi, we need to urgently replace the Discord link on our Jumper UI burger menu to the new discord invite link: https://discord.gg/jumperexchange. 
It was changed from our previous ‘ /LIFI’ and that currently redirects to another server which is not ours.
```
https://discord.com/channels/849912621360218112/1267141147248169013
=> fix: Discord link (prod)

src/components/Blog/BlogArticleCard/BlogArticleCard.style.ts
Ticket: https://lifi.atlassian.net/browse/LF-9572
Fixes thumbnail images with wrong aspect-ratio to "cover" the area.
=> style: provide fallback aspect-ratio for blog article card images

src/components/Alerts/InfoAlert/InfoAlertClickable.tsx, src/components/Blog/BlogArticle/BlogArticle.style.ts, src/components/Blog/BlogArticlesBoard/BlogArticlesBoard.style.ts, src/components/Blog/BlogArticlesBoard/BlogArticlesBoardTabs.tsx, src/components/Blog/BlogArticlesCollections/BlogArticlesCollections.style.ts, src/components/Blog/BlogCarousel/BlogCarousel.style.ts, src/components/Blog/CTAs/InstructionsAccordion/InstructionsAccordionItem.style.ts, src/components/Blog/CustomRichBlocks.style.ts, src/components/Blog/FeaturedArticle/FeaturedArticle.style.ts, src/components/Button/Button.style.ts, src/components/JoinDiscordBanner/JoinDiscordBanner.style.ts, src/components/OnRamper/OnRamper.tsx, src/components/Tabs/Tabs.style.ts, src/components/Tag.style.ts, src/components/WelcomeScreen/ToolModal/ToolModal.style.ts
Ticket: https://lifi.atlassian.net/browse/LF-10129
=> refactor: use text colors from text.primary palette

src/components/PromoLabel.style.ts
Before:
After:
✅  lowercase
✅  saving 2px vertically
✅  saving 4px horizontally
=> style: lower size of promo-label

src/components/FeatureCards/FeatureCard.style.tsx, src/components/Menu/SubMenu.tsx
1.) feature-card cta label attribute issue
2.) submenu list-item as children of list-item
=> fix: html DOM issues

src/components/Lightbox/Lightbox.tsx
Fixed a small typo in the Lightbox.tsx component where "udnerstand" was misspelled as "understand" in the comment explaining the width and height settings.
This is a minor documentation fix that improves code readability.
=> fix: typo in Lightbox component comment

.github/workflows/playwright.yml, playwright.config.ts
previously playwright reports were distributed between different shards, but this resulted in different reports for each shard. In this PR the reports will be merged into one.
[LF-13741](https://lifi.atlassian.net/browse/LF-13741)
---
---
[html-report--attempt-1.zip](https://github.com/user-attachments/files/20288629/html-report--attempt-1.zip)
=> LF-13741 merge playwright reports from different shards
